modLoader="javafml"
loaderVersion="[60.1,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="cspirit"
    namespace="cspirit"
    version="1.0.14"
    displayName="Christmas Spirit"
    authors="Calemi, Kryto627, CaptainKray, Jared"
    description='''
    ♫ Deck the mines with boughs of holly! ♫

    Wrap presents, eat holiday sweets, and decorate your Minecraft world with Christmas-themed features!
    '''

[[dependencies.cspirit]]
    modId="forge"
    mandatory=true
    versionRange="[60.1.0,)"
    ordering="NONE"
    side="BOTH"